config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'
if Octobox.config.sidekiq_schedule_enabled?
  require 'sidekiq-scheduler/web'
end
require 'sidekiq_unique_jobs/web'
require 'admin_constraint'

Rails.application.routes.draw do
  root to: 'notifications#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  constraints AdminConstraint.new do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end

    get '/admin', to: 'admin#index', as: :admin
  end

  mount ActionCable.server => '/cable'

  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'

  scope :auth do
    match '/:provider/callback', to: 'sessions#create',  via: [:get, :post]
    match :failure,              to: 'sessions#failure', via: [:get, :post]
  end

  resources :notifications, only: :index, format: true, constraints: { format: :json }
  resources :notifications, only: [] do
    collection do
      post :archive_selected
      post :sync
      get  :sync
      get  :syncing
      post :syncing
      post :mute_selected
      post :mark_read_selected
      get  :unread_count
      post :delete_selected
    end

    member do
      get  :show
      post :star
      get  :expand_comments
      post :comment 
    end
  end

  get '/documentation', to: 'pages#documentation'
  get '/support', to: redirect('/documentation#support')

  post '/hooks/github', to: 'hooks#create'

  # Octobox.io specific routes
  get '/opencollective', to: 'open_collective#callback'
  get '/pricing', to: 'pages#pricing'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'

  resources :pinned_searches

  get '/settings', to: 'users#edit'
  resources :users, only: [:update, :destroy] do
    collection do
      scope format: true, constraints: { format: 'json' } do
        get :profile
      end
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  REASON_LABELS = {
    'comment'        => 'primary',
    'author'         => 'success',
    'state_change'   => 'info',
    'mention'        => 'warning',
    'assign'         => 'danger',
    'subscribed'     => 'subscribed',
    'team_mention'   => 'team_mention',
    'security_alert' => 'security_alert'
  }.freeze

  STATE_LABELS = {
    'open'   => 'success',
    'closed' => 'danger',
    'merged' => 'subscribed'
  }

  SUBJECT_TYPES = {
    'RepositoryInvitation'         => 'mail-read',
    'Issue'                        => 'issue-opened',
    'PullRequest'                  => 'git-pull-request',
    'Commit'                       => 'git-commit',
    'Release'                      => 'tag',
    'RepositoryVulnerabilityAlert' => 'alert'
  }.freeze

  SUBJECT_STATUS = {
    success: "success",
    failure: "failure",
    error: "error",
    pending: "pending"
  }

  NOTIFICATION_STATUS_OCTICON = {
    'success' => 'check',
    'failure' => 'x',
    'error' => 'alert',
    'pending' => 'primitive-dot'
  }

  def filters
    {
      reason:          params[:reason],
      unread:          params[:unread],
      repo:            params[:repo],
      type:            params[:type],
      archive:         params[:archive],
      starred:         params[:starred],
      owner:           params[:owner],
      per_page:        params[:per_page],
      q:               params[:q],
      state:           params[:state],
      label:           params[:label],
      author:          params[:author],
      bot:             params[:bot],
      unlabelled:      params[:unlabelled],
      assigned:        params[:assigned],
      is_private:      params[:is_private],
      status:          params[:status],
    }
  end

  def inbox_selected?
    !archive_selected? && !starred_selected? && !showing_search_results?
  end

  def archive_selected?
    filters[:archive].present?
  end

  def starred_selected?
    filters[:starred].present?
  end

  def showing_search_results?
    filters[:q].present?
  end

  def show_archive_icon?
    starred_selected? || showing_search_results?
  end

  def notification_param_keys
    filters.keys - [:per_page]
  end

  def bucket_param_keys
    [:archive, :starred]
  end

  def filter_param_keys
    notification_param_keys - bucket_param_keys
  end

  def any_active_filters?
    filter_param_keys.any?{|param| filters[param].present? }
  end

  def filtered_params(override = {})
    filters.merge(override)
  end

  def mute_button
    function_button('Mute', 'mute', "mute", 'Mute notification', false)
  end

  def delete_button
    function_button("Delete", 'trashcan', "delete", 'Delete notification', false)
  end

  def archive_button
    function_button("Archive", 'checklist', "archive_toggle archive", 'Archive', false)
  end

  def unarchive_button
    function_button("Unarchive", 'inbox', "archive_toggle unarchive", 'Unarchive notification', false)
  end

  def mute_selected_button
    function_button('Mute selected', 'mute', 'mute_selected', 'Mute selected items')
  end

  def mark_read_selected_button
    function_button('Mark as read', 'eye', 'mark_read_selected', 'Mark items as read')
  end

  def archive_selected_button
    function_button("Archive selected", 'checklist', "archive_toggle archive_selected", 'Archive selected items')
  end

  def unarchive_selected_button
    function_button("Unarchive selected", 'inbox', "archive_toggle unarchive_selected", 'Unarchive selected items')
  end

  def delete_selected_button
    function_button("Delete selected", 'trashcan', "delete_selected", 'Delete selected items')
  end

  def select_all_button(cur_selected, total)
    button_tag(type: 'button', class: "select_all btn btn-sm btn-outline-dark hidden-button", 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': "Number of items selected") do
      octicon('check', height: 16) +
        content_tag(:span, " #{cur_selected}", class: 'bold d-none d-md-inline-block ml-1') +
        " | " +
        content_tag(:span, " #{total}", class: 'd-none d-md-inline-block')
    end if cur_selected < total
  end

  def function_button(title, octicon, css_class, tooltip, hidden=true)
    button_tag(type: 'button', class: "#{css_class} btn btn-sm btn-outline-dark #{'hidden-button' if hidden}", 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': tooltip ) do
      octicon(octicon, height: 16) + content_tag(:span, "#{title}", class: 'd-none d-xl-inline-block ml-1')
    end
  end

  def no_url_filter_parameters_present
    notification_param_keys.all?{|param| params[param].blank? }
  end

  def notification_icon(notification)
    subject_type = notification.subject_type
    state = notification.user.try(:github_app_authorized?) ? notification.state : nil
    return 'issue-closed' if subject_type == 'Issue' && state == 'closed'
    return 'git-merge' if subject_type == 'PullRequest' && state == 'merged'
    subject_type_icon(subject_type)
  end

  def subject_type_icon(subject_type)
    SUBJECT_TYPES[subject_type]
  end

  def notification_icon_title(notification)
    return "Draft #{notification.subject_type.underscore.humanize.downcase}" if notification.draft?
    return notification.subject_type.underscore.humanize if notification.state.blank?
    "#{notification.state.underscore.humanize} #{notification.subject_type.underscore.humanize.downcase}"
  end

  def notification_icon_color(notification)
    return unless notification.display_subject?
    return 'text-draft' if notification.draft?
    {
      'open' => 'text-success',
      'closed' => 'text-danger',
      'merged' => 'text-subscribed'
    }[notification.state]
  end

  def reason_label(reason)
    REASON_LABELS.fetch(reason, 'secondary')
  end

  def state_label(state)
    STATE_LABELS.fetch(state, 'secondary')
  end

  def filter_option(param)
    if filters[param].present?
      link_to root_path(filters.except(param)), class: "btn btn-sm btn-outline-dark" do
        concat octicon('x', :height => 16)
        concat ' '
        concat yield
      end
    end
  end

  def reason_filter_option(reason)
    if filters[:reason].present? && reason.present?
      reasons = filters[:reason].split(',').reject(&:empty?)
      index = reasons.index(reason.underscore.downcase)
      reasons.delete_at(index) if index
      link_to root_path(filters.merge(:reason => reasons.join(','))), class: "btn btn-sm btn-outline-dark" do
        concat octicon('x', :height => 16)
        concat ' '
        concat yield
      end
    end
  end

  def filter_link(param, value, count)
    sidebar_filter_link(active: params[param] == value.to_s, param: param, value: value, count: count) do
      yield
    end
  end

  def org_filter_link(param, value)
    sidebar_filter_link(active: params[param] == value.to_s, param: param, value: value, except: :repo, link_class: 'owner-label') do
      yield
    end
  end

  def repo_filter_link(param, repo_name, count)
    active = params[param] == repo_name || params[:owner] == repo_name.split('/')[0]
    sidebar_filter_link(active: active, param: param, value: repo_name, count: count, except: :owner, link_class: 'repo-label', title: repo_name) do
      yield
    end
  end

  def sidebar_filter_link(active:, param:, value:, count: nil, except: nil, link_class: nil, path_params: nil, title: nil)
    css_class = 'nav-item'
    css_class += ' active' if active
    css_class += " #{param}-#{value}"

    content_tag :li, class: css_class, title: title do
      active = (active && not_repo_in_active_org(param))
      path_params ||= filtered_params(param => (active ? nil : value)).except(except)
      link_to root_path(path_params), class: (active ? "nav-link active filter #{link_class}" : "nav-link filter #{link_class}") do
        yield
        if active && not_repo_in_active_org(param)
          concat content_tag(:span, octicon('x', :height => 16), class: 'badge badge-light')
        elsif count.present?
          concat content_tag(:span, count, class: 'badge badge-light')
        end
      end
    end
  end

  def reason_filter_link(value, count)
    active = params[:reason].present? && params[:reason].split(',').include?(value.to_s)
    link_value = reason_link_param_value(params[:reason], value, active)
    path_params = filtered_params(:reason => link_value)

    sidebar_filter_link(active: active, param: :reason, value: link_value, count: count, path_params: path_params) do
      yield
    end
  end

  def reason_link_param_value(param, value, active)
    reasons = param.try(:split, ',') || []
    active ? reasons.delete(value) : reasons.push(value)
    reasons.try(:join, ',')
  end

  def not_repo_in_active_org(param)
    return true unless param == :repo
    params[:owner].blank?
  end

  def search_query_matches?(query, other_query)
    query.split(' ').sort == other_query.split(' ').sort
  end

  def search_pinned?(query)
    return unless query.present?
    return false if current_user.pinned_searches.empty?

    current_user.pinned_searches.any? do |pinned_search|
      search_query_matches?(query, pinned_search.query)
    end
  end

  def notification_status(status)
    return unless status.present?
    content_tag(:span,
      octicon(NOTIFICATION_STATUS_OCTICON[status], height: 16, class: status),
      class: "badge badge-light badge-pr #{status}",
      title: status.humanize,
      data: {toggle: 'tooltip'}
    )
  end

  def sidebar_notification_status(status)
    octicon(NOTIFICATION_STATUS_OCTICON[status], height: 16, class: "sidebar-icon #{status}")
  end

  def subject_with_number(notification)
    if ['Issue', 'PullRequest'].include?(notification.subject_type)
      capture do
        concat content_tag(:span, "##{notification.subject_number}", class: "notification-number")
        concat " "
        concat notification.subject_title
      end
    else
      notification.subject_title
    end
  end

  def notification_button(subject_type, state = nil)

app/views/notifications/_help-box.html.erb
<div id="help-box" class="modal" role="dialog">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Keyboard shortcuts</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= render 'shared/keyboard_mappings' %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/_list.html.erb
<div class="card card-notifications justify-content-between">
  <div class="card-header sticky-top">
    <% if @notifications.to_a.any? %>
      <div class="per-page btn-group float-right d-block" data-toggle="tooltip" data-placement="left" title="Notifications per page">
        <button type="button" class="btn btn-sm btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= @per_page %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right text-right">
          <% %w(10 20 40 60 80 100).map do |pagination_interval| %>
            <%= link_to pagination_interval, root_path(filtered_params(per_page: pagination_interval.to_i)), class: "dropdown-item #{'active' if @per_page == pagination_interval.to_i}" %>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="btn btn-sm btn-link help float-right d-none d-md-inline-block" data-toggle="modal" data-target="#help-box">
      <%= octicon 'keyboard', :height => 16 %>
    </div>
    <button id='sidebar_toggle' type="button" class="d-inline-block d-lg-none btn btn-sm btn-outline-dark" data-toggle="offcanvas" aria-label='Toggle sidebar'>
      <%= octicon 'three-bars', :height => 16 %>
    </button>
    <% if @notifications.to_a.any? %>
      <div class="custom-control custom-checkbox select-all d-inline-block">
        <input id="select_all" type="checkbox" autocomplete="off" class='custom-control-input js-select_all' aria-label='Select All'>
        <%= label_tag "select_all", '', class: "custom-control-label" %>
      </div>
      <%= select_all_button(@cur_selected, @total) %>
    <% end %>
    <%= link_to sync_notifications_path(filters), class: "btn btn-sm btn-outline-dark js-sync #{'js-async' if Octobox.background_jobs_enabled?}", 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'data-turbolinks' => false, 'data-animation' => 'false', 'data-position' => 'bottom', 'title' => 'Sync', 'aria-label' => 'Sync' do %>
      <%= octicon 'sync', height: 16, class: "#{'spinning' if initial_sync? || current_user.syncing?}" %>
    <% end %>
    <%= archive_selected_button unless archive_selected? %>
    <%= unarchive_selected_button unless inbox_selected? %>
    <%= mute_selected_button %>
    <%= mark_read_selected_button %>
    <%= delete_selected_button unless inbox_selected? %>
    <%= render 'filter-list' %>
    <% if current_user.last_synced_at %>
      <span class='text-muted d-none d-sm-inline-block'>
        <small>Last sync: <%= time_ago_in_words current_user.last_synced_at %> ago</small>
      </span>
    <% end %>
  </div>

  <table class='table table-hover table-notifications js-table-notifications mb-0 <%= 'filtered' if any_active_filters? %>' data-refresh-interval=<%= current_user.effective_refresh_interval %>>
    <% if @notifications.to_a.any? %>
      <%= render partial: 'notification', collection: @notifications %>
    <% elsif initial_sync? %>
      <div class="py-5 text-center js-initial_sync">
        <%= octicon 'cloud-download', height: 32, class: 'blankslate-icon' %>
        <h3>Syncing your notifications for the first time...</h3>
        <p>This might take a minute or two</p>
      </div>
      <% unless current_user.syncing? %>
        <span class="js-start_sync"><!-- This causes a sync to occur --></span>
      <% end %>
    <% elsif no_url_filter_parameters_present %>
      <div class="py-5 text-center">
        <%= octicon 'thumbsup', height: 32, class: 'blankslate-icon' %>
        <h3>You're in the clear!</h3>
        <p>There are no notifications that need your attention.</p>
        <p>
          <%= link_to sync_notifications_path(filters), method: :post, class: 'btn btn-outline-secondary sync' do %>
            <%= octicon 'sync', height: 18 %>
            <span class='ml-1'>Refresh</span>
          <% end %>
        </p>
        <% unless current_user.notifications.any? %>
          <p><i>Expecting notifications? Make sure <a href="<%= Octobox.config.github_domain %>/settings/notifications">Web Notifications</a> are enabled on your GitHub account.</i></p>
        <% end %>
        <% if current_user.last_synced_at %>
          <p class='text-muted'>
            <small>Last sync: <%= time_ago_in_words current_user.last_synced_at %> ago</small>
          </p>
        <% end %>
      </div>
    <% else %>
      <div class="py-5 text-center">
        <%= octicon 'search', height: 32, class: 'blankslate-icon' %>
        <h3>Nothing to see here.</h3>
        <p>You can always try <%= link_to 'refreshing', sync_notifications_path(filters), method: :post %> or <%= link_to 'removing filters', root_path %>.</p>
        <% unless current_user.notifications.any? %>
          <p><i>Expecting notifications? Make sure <a href="<%= Octobox.config.github_domain %>/settings/notifications">Web Notifications</a> are enabled on your GitHub account.</i></p>
        <% end %>
        <% if current_user.last_synced_at %>
          <p class='text-muted'>
            <small>Last sync: <%= time_ago_in_words current_user.last_synced_at %> ago</small>
          </p>
        <% end %>
      </div>
    <% end %>
  </table>
</div>

<div class="d-flex justify-content-center">
  <%== render 'pagination', pagy: @pagy %>
</div>

<%= render 'layouts/footer' %>

app/views/notifications/_notification.html.erb
<tr id='notification-<%= notification.id %>' class='notification <%= notification.unread ? 'active' : '' %> <%= notification.display? ? '' : 'notification-disabled' %>'>
  <td class='notification-checkbox align-middle'>
    <div class="custom-control custom-checkbox">
      <%= check_box_tag(
          "notification_#{notification.id}",
          notification.id,
          false,
          title: (notification.archived ? 'Unarchive' : 'Archive'),
          class: 'custom-control-input ' + (notification.archived ? 'unarchive' : 'archive'),
          autocomplete: "off"
        )
      %>
      <%= label_tag "notification_#{notification.id}", '', class: "custom-control-label" %>
    </div>
  </td>
  <td class='notification-star align-middle'>
    <%= octicon 'star', height: 18, class: "toggle-star #{notification.starred ? 'star-active' : 'star-inactive'}", data: { id: notification.id, toggle: 'tooltip' }, title: notification.starred ? 'Remove star' : 'Star' %>
  </td>

  <td class='notification-archived align-middle'>
    <% if notification.archived? %>
      <%= octicon 'archive', height: 16, data: { toggle: 'tooltip' }, title: 'Archived' %>
    <% end %>
  </td>

  <% if notification.display? %>
    <td class='notification-icon align-middle <%= notification_icon_color(notification) %>'>
      <% if Octobox.github_app? && notification.subjectable? %>
        <% if notification.repository.try(:github_app_installed?) && !notification.user.try(:github_app_authorized?) %>
          <a tabindex="0" class="" role="button" data-toggle="popover" title="Login to the GitHub App" data-content="<%= render 'notifications/login_prompt' %>">
            <%= octicon notification_icon(notification), :height => 16 %>
          </a>
        <% elsif !notification.repository.try(:github_app_installed?) %>
          <a tabindex="0" class="" role="button" data-toggle="popover" title="Get more info for this <%= notification_icon_title(notification) %>" data-content="<%= render 'notifications/app_prompt', notification: notification %>">
            <%= octicon notification_icon(notification), :height => 16 %>
          </a>
        <% elsif Octobox.io? && notification.upgrade_required? %>
          <a tabindex="0" class="" role="button" data-toggle="popover" title="Subscribe Now" data-content="<%= render 'notifications/private_repos' %>">
            <%= octicon notification_icon(notification), :height => 16 %>
          </a>
        <% else %>
          <%= octicon notification_icon(notification), :height => 16, title: notification_icon_title(notification), data: {toggle: 'tooltip'} %>
        <% end %>
      <% else %>
        <%= octicon notification_icon(notification), :height => 16, title: notification_icon_title(notification), data: {toggle: 'tooltip'} %>
      <% end %>
    </td>
    <td class='notification-subject'>
      <%= link_to notification_link(notification), target: (Octobox.config.open_in_same_tab ? nil : '_blank'), rel: "noopener", class: "link #{'thread-link' if notification.display_thread?}", onclick: "Octobox.markRead(#{notification.id})", data:{toggle:(notification.display_thread? ? 'showthread' : nil)}, title: notification.title do %>
          <%= subject_with_number(notification) %>
          <%= octicon('link-external', class:'text-primary') unless notification.display_thread? %>
      <% end %>

      <% if notification.display_subject? %>
        <% if notification.subject %>
          <% notification.subject.labels.each do |label| %>
            <%= link_to emojify(label.name), root_path(filtered_params(label: label.name)), class: "badge d-sm", style: "background-color: ##{label.color}; color: #{label.text_color}" %>
          <% end %>
          <%= notification_status(notification.subject.status) %>
        <% end %>
      <% end %>
    </td>

    <td class='notification-repo'>
      <% unless params[:repo].present? %>
        <small>
          <%= link_to notification.repository_full_name, root_path(filtered_params(repo: notification.repository_full_name)), class: 'text-muted' %>
        </small>
      <% end %>
    </td>

    <td class='notification-subject-author'>
      <% if notification.display_subject? %>
        <% if notification.subject && notification.subject.author %>
          <small>
            <%= link_to notification.subject.author, root_path(filtered_params(author: notification.subject.author)), class: 'text-muted', title: 'Author', data: {toggle: 'tooltip'} %>
          </small>
        <% end %>
      <% end %>
    </td>

    <td class='notification-reason'>
      <%= link_to notification.reason.humanize, root_path(filtered_params(reason: notification.reason)), class: "badge badge-#{reason_label(notification.reason)}" %>
    </td>
  <% else %>

    <td class='notification-icon align-middle'>
      <%= octicon('lock', height: 16) %>
    </td>
    <td class='notification-subject'>
      Private notification on <strong><%= notification.repository_full_name %></strong>,
      <%= link_to 'upgrade', pricing_path %> to unlock.
    </td>

    <td class='notification-repo'>
      <% unless params[:repo].present? %>
        <small>
          <%= link_to notification.repository_full_name, root_path(filtered_params(repo: notification.repository_full_name)), class: 'text-muted' %>
        </small>
      <% end %>
    </td>

    <td class='notification-subject-author'></td>
    <td class='notification-reason'></td>
  <% end %>

  <td class='notification-date'>
    <% if notification.display_subject? && notification.subject %>
      <span class='badge badge-light n notification-comment-count mr-2'>
        <%= octicon 'comment', height: 10%>
        <%= notification.subject.comment_count %>
      </span>
    <% end %>

    <small class='text-muted'>
      <%= local_relative_time(notification.updated_at, type: 'time-or-date') %>
    </small>

    <span class='buttons'>
      <% if notification.archived? %>
        <%= link_to(archive_selected_notifications_path(id: notification.id, value: false), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Unarchive' ) do %>
          <%= octicon('inbox', height: 15) %>
        <% end %>
      <% else %>
        <%= link_to(archive_selected_notifications_path(id: notification.id), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Archive' ) do %>
          <%= octicon('archive', height: 15) %>
        <% end %>
      <% end %>
      <%= link_to(mute_selected_notifications_path(id: notification.id), method: :post,  'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Mute', 'data-confirm': "Are you sure you want to mute?") do %>
        <%= octicon('mute', height: 15) %>
      <% end %>
      <% if notification.archived? %>
        <%= link_to(delete_selected_notifications_path(id: notification.id), class: 'ml-1', method: :post, 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Delete', 'data-confirm': "Are you sure you want to delete?") do %>
          <%= octicon('trashcan', height: 15) %>
        <% end %>
      <% end %>
    </span>
  </td>
</tr>

app/views/notifications/_reply.html.erb
<%= form_tag comment_notification_path, method: :post, class: 'card mt-3', id: 'reply', enforce_utf8: false do |f| %>
	<div class='card-header'>
		<%= image_tag current_user.github_avatar_url + "?size=20", width: 20, class: 'img-rounded navbar-avatar', alt: '' %>
	</div>
	<div class='card-body justify-content-right'>
		<%= text_area(:comment, :body, class: 'form-control', placeholder: 'Leave a comment') %>
		<%= submit_tag("Comment", class: 'btn mt-2 ml-2 btn-success float-right') %>
		<%= link_to "View on GitHub", @notification.subject.html_url, class:"btn btn-light mt-2 float-right", target: "_blank"%>
 		<%= hidden_field(:id, @notification.id) %>
 	</div>
<% end %>

app/views/notifications/_thread.html.erb
<div class='d-flex card-header sticky-top justify-content-between'>
  <div>
    <button class="btn btn-sm btn-outline-dark toggle-star <%=@notification.starred ? 'star-active' : 'star-inactive' %>" data-id= <%=@notification.id%> title=<%= @notification.starred ? 'Remove star' : 'Star'%> data-toggle='tooltip'>
      <%= octicon 'star', height: 18%>
    </button>
    <%= archive_button unless archive_selected? %>
    <%= unarchive_button unless inbox_selected? %>
    <%= mute_button %>
    <%= delete_button %>
  </div>
  <div>
    <% if @previous %>
      <%= link_to octicon('chevron-left'), notification_path(filtered_params(id: @previous)), class: "btn btn-sm previous btn-outline-dark", data:{toggle:'tooltip', placement:'auto'}, title:'Previous notification' %>
    <% else %>
      <%= link_to octicon('chevron-left'), '#', class: "btn btn-sm previous btn-outline-secondary" %>
    <% end %>
    <% if @next %>
      <%= link_to octicon('chevron-right'), notification_path(filtered_params(id: @next)), class: "btn btn-sm next btn-outline-dark", data:{toggle:'tooltip', placement:'auto'}, title:'Next notification' %>
    <% else %>
      <%= link_to octicon('chevron-right'), '#', class: "btn btn-sm next btn-outline-secondary" %>
    <% end %>
    <%= link_to octicon('x'), root_path(filtered_params), class: 'btn btn-sm closethread btn-outline-dark d-xxxl-none', data:{toggle: 'tooltip'}, title: 'Close discussion' %>
  </div>
</div>

<div id='notification-thread' class="p-3 mb-5" data-id='<%= @notification.id %>' data-subject-id='<%= @notification.subject.id %>'>

  <div id='thread-subject'>
    <%= render 'thread_subject', notification: @notification %>
  </div>

  <% if @notification.subject %>
    <div class='discussion-thread'>
      <% if @notification.subject.body %>
        <div class="card-comment card mt-3">
          <div class="card-header media d-flex align-items-center">

            <%= image_tag(avatar_url(@notification.subject.author), width: 20, class: 'mr-3 align-self-center') %>

            <div class='media-body text-muted'>

              <b><%= link_to @notification.subject.author, Octobox.config.github_domain+'/'+@notification.subject.author_url_path, class: 'text-muted'%></b> commented <span class='text-muted'><%= time_ago_in_words(@notification.subject.created_at) %></span> ago
            </div>
          </div>
          <div class="card-body">
            <article class="markdown-body">
              <% if @notification.subject.body.present? %>
                <%== parse_markdown(@notification.subject.body) %>
              <% else %>
                <p>
                  <i>No description given.</i>
                </p>
              <% end %>
            </article>
          </div>
        </div>
      <% end %>
      <% if @notification.subject.commentable? %>
        <% if @comments_left_to_load > 0 %>
          <div id='more-comments'>
            <%= link_to expand_comments_notification_url, class: 'btn btn-secondary mt-3 expand_comments' do %>
              <%= octicon('comment', height: 16, class: 'ml-1') %>
              View <%= @comments_left_to_load %> more comments
            <% end %>
          </div>
        <% end %>

        <% @comments.each_with_index do |comment, index| %>
          <%= render partial: 'comment', locals:{comment: comment, index: index} %>
        <% end %>
      <% end %>
      
    </div>

    <% if current_user.can_comment?(@notification.subject)%>
      <%= render partial: 'reply', locals: {notification: @notification} %>
    <% end %>
  <% end %>
</div>